accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns= [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
]

articles/urls.py
from pathlib import Path
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

"""
리뷰 제목 (30자 이하)
리뷰 내용
영화 이름
영화 평점
리뷰 작성시간
리뷰 수정시간
"""

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=50)
    grade = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='images/', blank=True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(400, 300)],
                                format='JPEG',
                                options={'quality': 100})
    
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

accounts/forms.py
from pyexpat import model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')
        # 생일은 어떻게 넣을 수 있을까?
        labels = {
            'username': '아이디'
        }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    grade = forms.FloatField(
        required=True,
        max_value=5,
        min_value=1,
        widget=forms.NumberInput(attrs={"step": "0.5"}),
    )
    class Meta:
        model = Article
        fields = "__all__"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, update_session_auth_hash
# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    users = get_user_model().objects.order_by('-pk')
    context = {
        'users': users,
    }
    return render(request, 'accounts/index.html', context)


def signup(request):
    # 이미 로그인 한 사람은 articles:index로 보내기
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        # POST 요청 처리
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                return redirect('accounts:index')
        else:
            form = CustomUserCreationForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/signup.html', context)
    

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    else:
        if request.method == 'POST':
            # AuthenticationForm은 ModelForm이 아님
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                # 세션에 저장
                # login 함수는 request, user 객체를 인자로 받음
                # user 객체는 form에서 인증된 유저 정보
                auth_login(request, form.get_user())
                return redirect('articles:index')
        else:
            form = AuthenticationForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/login.html', context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:detail', request.user.pk)
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/change_password.html', context)
    

def logout(request):
    auth_logout(request)
    return redirect('index')


@login_required
def delete(request):
    # 선 탈퇴
    request.user.delete()
    # 후 로그아웃
    auth_logout(request)
    return redirect('index')

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm
from .models import Article, Comment
from django.views.decorators.http import require_http_methods

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    # GET이 아닌 POST 사용
    if request.method == 'POST':
        # DB에 저장
        article_form = ArticleForm(request.POST, request.FILES)
        # print(request.FILES)
        # 유효성 검사
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:index')
    else:
        # 유효하지 않은 경우
        # 이슈가 발생한 페이지를 보여주고 정정하라고 함
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/create.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES, instance=article)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm(instance=article)
    context = {
        'article': article,
        'article_form': article_form
    }
    return render(request, 'articles/update.html', context)


def delete(request, pk):
    Article.objects.get(pk=pk).delete()
    return redirect('articles:index')

config/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="container d-flex justify-content-center my-5">
    <div class="card col-8 bg-light">
      <h1 class="text-center my-4 fs-3 fw-bold">Change Password</h1>
      <div class="card-body">
        <form action="{% url 'accounts:change_password' %}" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="mt-4">
            <button class="btn btn-primary me-2" type="submit">SAVE</button>
            <a class=" btn btn-outline-secondary" href="{% url 'accounts:detail' user.pk %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <div class="container d-flex flex-column align-items-center">
    <div class="card mt-5 mb-4" style="width: 25rem;">
      <div class="card-header text-bg-dark">
        <h5 class="fs-3 fw-bold text-center my-1">
          {{ user.username }}
        </h5>
      </div>
      <div class="card-body d-flex justify-content-center">
        <img src="{% static '프사.jpg' %}" class="card-img-top rounded-1" style="width: 20rem; height: 20rem;" alt="...">
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ user.first_name }}
          {{ user.last_name }}</li>
        <li class="list-group-item">{{ user.email }}</li>
      </ul>
    </div>
    {% if request.user == user %}
      <div class="mb-5">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Edit
          </button>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'accounts:update' %}" role="button">Edit My Info</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:change_password' %}" role="button">Change Password</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item text-danger" href="{% url 'accounts:delete' %}" role="button">Delete My Account</a>
            </li>
          </ul>
        </div>
        <a class=" btn btn-outline-secondary ms-3" href="{% url 'accounts:index' %}" role="button">Back</a>
      </div>
    {% else %}
      <a class=" btn btn-outline-secondary" href="{% url 'accounts:index' %}" role="button">Back</a>
    {% endif %}
  </div>
</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container">
    <h1 class="text-center mt-5 mb-4 fw-bold fs-2">All Users</h1>
    <table class="table table-hover">
      <thead class="table-info">
        <tr>
          <th scope="col">pk</th>
          <th scope="col">Username</th>
          <th scope="col">Emial</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for user in users %}
          <tr>
            <th scope="row">{{ user.pk }}</th>
            <td>
              <a href="{% url 'accounts:detail' user.pk %}">
                {{ user.username }}
              </a>
            </td>
            <td>{{ user.email }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <a class="btn btn-outline-danger" href="{% url 'accounts:logout' %}" role="button">Sign Out</a>
  </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="container d-flex justify-content-center my-5">
    <div class="card col-8 bg-light">
      <h1 class="text-center my-4 fs-3 fw-bold">Sign In</h1>
      <div class="card-body">
        <form action="" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="mt-4">
            <button class="btn btn-primary me-2" type="submit">GO</button>
            <a class=" btn btn-outline-secondary" href="{% url 'index' %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="container d-flex justify-content-center my-5">
    <div class="card col-8 bg-light">
      <h1 class="text-center my-4 fs-3 fw-bold">Sign Me UP!</h1>
      <div class="card-body">
        <form action="" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="mt-4">
            <button class="btn btn-success me-2" type="submit">JOIN</button>
            <a class=" btn btn-outline-secondary" href="{% url 'index' %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="container d-flex justify-content-center my-5">
    <div class="card col-8 bg-light">
      <h1 class="text-center my-4 fs-3 fw-bold">Edit Profile</h1>
      <div class="card-body">
        <form action="" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="mt-4">
            <button class="btn btn-primary me-2" type="submit">SAVE</button>
            <a class=" btn btn-outline-secondary" href="{% url 'accounts:detail' user.pk %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container d-flex justify-content-center my-5">
    <div class="card col-8 bg-light">
      <h1 class="text-center my-4 fs-3 fw-bold">Add New Post</h1>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form article_form %}
          <div class="mt-4">
            <button class="btn btn-primary me-2" type="submit">Add</button>
            <a class=" btn btn-outline-secondary" href="{% url 'articles:index' %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <h1>상세보기</h1>
  <img src="{% static 'articles/카톡 프로필.jpg' %}" alt="img">
  <h5>{{ article.pk }}번째 게시글</h5>
  <h1>{{ article.title }}</h1>
  <p>Created :
    {{ article.created_at }}
    | Updated :
    {{ article.updated_at }}</p>
  <p>{{ article.content }}</p>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <h5>Comments</h5>
  <hr>
  {% for comment in article.comment_set.all %}
    <p>{{ comment.content }}</p>
    <hr>
    {% empty %}
    <p>No comments yet.</p>
  {% endfor %}
  <a class=" btn btn-outline-primary" href="{% url 'articles:update' article.pk %}" role="button">Edit</a>
  <a class=" btn btn-outline-danger" href="{% url 'articles:delete' article.pk %}" role="button">Delete</a>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container">
    <h1 class="text-center my-5 fw-bold fs-2">All Posts</h1>
    <a href="{% url 'articles:create' %}" class="btn btn-primary">Add</a>
    <div class="row row-cols-1 row-cols-md-4 g-5 mt-1">
      {% for article in articles %}
        <div class="col my-4">
          <a class="text-decoration-none" href="{% url 'articles:detail' article.pk %}">
            <div class="card h-100">
              <img src="{{ article.images.url }}" alt="{{ article.images }}" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Movie Name :
                  {{ article.movie_name }}</li>
                <li class="list-group-item">Rating :
                  {{ article.grade }}</li>
              </ul>
              <div class="card-footer">
                <small class="text-muted">Last updated :
                  {{ article.updated_at }}</small>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  {% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container d-flex justify-content-center my-5">
    <div class="card col-8 bg-light">
      <h1 class="text-center my-4 fs-3 fw-bold">Edit My Post</h1>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form article_form %}
          <div class="mt-4">
            <button class="btn btn-primary me-2" type="submit">SAVE</button>
            <a class=" btn btn-outline-secondary" href="{% url 'articles:detail' article.pk %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>221014 Pjt</title>
    {% bootstrap_css %}
    {% block css %}{% endblock %}
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
      }

      .btn-success:hover {
        background-color: white;
        border-color: $success;
        color: #198754;
      }

      .btn-search {
        background-color: $dark;
        border-color: white;
        color: white;
      }

      .btn-search:hover {
        background-color: white;
        border-color: $white;
        color: $dark;
      }
    </style>
  </head>

  <body class="bg-light">
    <!-- Navbar -->
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand ms-5" href="{% url 'index' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link mx-3" aria-current="page" href="{% url 'articles:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link me-3" href="{% url 'accounts:index' %}">User</a>
            </li>
          </ul>
          <!-- 로그인 => Username 출력 -->
          <li class="nav-item">
            <span class="text-light">Hello,</span>
            <a class="navbar-brand nav-link mx-3" aria-current="page" href="#">{{ request.user.username }}</a>
            <a class="nav-link me-3 text-light" href="{% url 'accounts:logout' %}">Sign Out</a>
          </li>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-search me-5" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      {% block content %}{% endblock content %}
    </div>

    <footer class="text-center my-5 text-muted">
      Copyright 2022. 임선주
    </footer>

    {% bootstrap_javascript %}
  </body>

</html>

templates/index.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>221014 Pjt</title>
    {% bootstrap_css %}
    {% block css %}{% endblock %}
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
      }

      .btn-success:hover {
        background-color: white;
        border-color: $success;
        color: #198754;
      }
    </style>
  </head>

  <body class="bg-light">
    <div class="navbar bg-dark justify-content-center">
      <h1 class="my-5 fw-bold text-white">🎬 Welcome to MovieUs 🍿</h1>
    </div>      
    <div class="container-fluid text-center">
      <div class="row m-5 justify-content-center">
        <div class="col-sm-5 mt-4">
          <div class="card mx-5 position-relative" style="height:25rem;">
            <div class="card-body">
              <h4 class="card-title fw-bold my-5">Are you new here?</h3>
              {% comment %} <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> {% endcomment %}
              <a class="btn btn-success me-3 col-7 rounded-pill position-absolute top-50 start-50 translate-middle" href="{% url 'accounts:signup' %}" role="button">JOIN NOW</a>
            </div>
          </div>
        </div>
        <div class="col-sm-5 mt-4">
          <div class="card mx-5 position-relative" style="height:25rem;">
            <div class="card-body">
              <h4 class="card-title fw-bold my-5">Hello again!</h3>
              <a class="btn btn-outline-primary col-7 rounded-pill position-absolute top-50 start-50 translate-middle" href="{% url 'accounts:login' %}" role="button">Sign In</a>
            </div>
          </div>
        </div>
      </div>

      </div>

    <footer class="text-center my-5 text-muted">
      Copyright 2022. 임선주
    </footer>

    {% bootstrap_javascript %}
  </body>

</html>